namespace FeatureVotingSystem.Core.Reports.Features.UserReportRequests.GetUserRequestedFeaturesVotesQuantity;

public record UserRequestedFeatureVotesQuantityRequest(ReportTimeFrame reportTimeFrame);
